const countryInfo = [
    { name: "Afghanistan", flagURL: "https://cdn.countryflags.com/thumbs/afghanistan/flag-800.png" },
    { name: "Albania", flagURL: "https://cdn.countryflags.com/thumbs/albania/flag-800.png" },
    { name: "Algeria", flagURL: "https://cdn.countryflags.com/thumbs/algeria/flag-800.png" },
    { name: "Andorra", flagURL: "https://cdn.countryflags.com/thumbs/andorra/flag-800.png" },
    { name: "Angola", flagURL: "https://cdn.countryflags.com/thumbs/angola/flag-800.png" },
    { name: "Antigua and Barbuda", flagURL: "https://cdn.countryflags.com/thumbs/antigua-and-barbuda/flag-800.png" },
    { name: "Argentina", flagURL: "https://cdn.countryflags.com/thumbs/argentina/flag-800.png" },
    { name: "Armenia", flagURL: "https://cdn.countryflags.com/thumbs/armenia/flag-800.png" },
    { name: "Australia", flagURL: "https://cdn.countryflags.com/thumbs/australia/flag-800.png" },
    { name: "Austria", flagURL: "https://cdn.countryflags.com/thumbs/austria/flag-800.png" },
    { name: "Azerbaijan", flagURL: "https://cdn.countryflags.com/thumbs/azerbaijan/flag-800.png" },
    { name: "Bahamas", flagURL: "https://cdn.countryflags.com/thumbs/bahamas/flag-800.png" },
    { name: "Bahrain", flagURL: "https://cdn.countryflags.com/thumbs/bahrain/flag-800.png" },
    { name: "Bangladesh", flagURL: "https://cdn.countryflags.com/thumbs/bangladesh/flag-800.png" },
    { name: "Barbados", flagURL: "https://cdn.countryflags.com/thumbs/barbados/flag-800.png" },
    { name: "Belarus", flagURL: "https://cdn.countryflags.com/thumbs/belarus/flag-800.png" },
    { name: "Belgium", flagURL: "https://cdn.countryflags.com/thumbs/belgium/flag-800.png" },
    { name: "Belize", flagURL: "https://cdn.countryflags.com/thumbs/belize/flag-800.png" },
    { name: "Benin", flagURL: "https://cdn.countryflags.com/thumbs/benin/flag-800.png" },
    { name: "Bhutan", flagURL: "https://cdn.countryflags.com/thumbs/bhutan/flag-800.png" },
    { name: "Bolivia", flagURL: "https://cdn.countryflags.com/thumbs/bolivia/flag-800.png" },
    { name: "Bosnia and Herzegovina", flagURL: "https://cdn.countryflags.com/thumbs/bosnia-and-herzegovina/flag-800.png" },
    { name: "Botswana", flagURL: "https://cdn.countryflags.com/thumbs/botswana/flag-800.png" },
    { name: "Brazil", flagURL: "https://cdn.countryflags.com/thumbs/brazil/flag-800.png" },
    { name: "Brunei", flagURL: "https://cdn.countryflags.com/thumbs/brunei/flag-800.png" },
    { name: "Bulgaria", flagURL: "https://cdn.countryflags.com/thumbs/bulgaria/flag-800.png" },
    { name: "Burkina Faso", flagURL: "https://cdn.countryflags.com/thumbs/burkina-faso/flag-800.png" },
    { name: "Burundi", flagURL: "https://cdn.countryflags.com/thumbs/burundi/flag-800.png" },
    { name: "Cambodia", flagURL: "https://cdn.countryflags.com/thumbs/cambodia/flag-800.png" },
    { name: "Cameroon", flagURL: "https://cdn.countryflags.com/thumbs/cameroon/flag-800.png" },
    { name: "Canada", flagURL: "https://cdn.countryflags.com/thumbs/canada/flag-800.png" },
    { name: "Cape Verde", flagURL: "https://cdn.countryflags.com/thumbs/cape-verde/flag-800.png" },
    { name: "Central African Republic", flagURL: "https://cdn.countryflags.com/thumbs/central-african-republic/flag-800.png" },
    { name: "Chad", flagURL: "https://cdn.countryflags.com/thumbs/chad/flag-800.png" },
    { name: "Chile", flagURL: "https://cdn.countryflags.com/thumbs/chile/flag-800.png" },
    { name: "China", flagURL: "https://cdn.countryflags.com/thumbs/china/flag-800.png" },
    { name: "Colombia", flagURL: "https://cdn.countryflags.com/thumbs/colombia/flag-800.png" },
    { name: "Comoros", flagURL: "https://cdn.countryflags.com/thumbs/comoros/flag-800.png" },
    { name: "Congo, Democratic Republic of the", flagURL: "https://cdn.countryflags.com/thumbs/congo-democratic-republic-of-the/flag-800.png" },
    { name: "Congo, Republic of the", flagURL: "https://cdn.countryflags.com/thumbs/congo-republic-of-the/flag-800.png" },
    { name: "Costa Rica", flagURL: "https://cdn.countryflags.com/thumbs/costa-rica/flag-800.png" },
    { name: "Croatia", flagURL: "https://cdn.countryflags.com/thumbs/croatia/flag-800.png" },
    { name: "Cuba", flagURL: "https://cdn.countryflags.com/thumbs/cuba/flag-800.png" },
    { name: "Cyprus", flagURL: "https://cdn.countryflags.com/thumbs/cyprus/flag-800.png" },
    { name: "Czech Republic", flagURL: "https://cdn.countryflags.com/thumbs/czech-republic/flag-800.png" },
    { name: "Denmark", flagURL: "https://cdn.countryflags.com/thumbs/denmark/flag-800.png" },
    { name: "Djibouti", flagURL: "https://cdn.countryflags.com/thumbs/djibouti/flag-800.png" },
    { name: "Dominica", flagURL: "https://cdn.countryflags.com/thumbs/dominica/flag-800.png" },
    { name: "Dominican Republic", flagURL: "https://cdn.countryflags.com/thumbs/dominican-republic/flag-800.png" },
    { name: "East Timor", flagURL: "https://cdn.countryflags.com/thumbs/east-timor/flag-800.png" },
    { name: "Ecuador", flagURL: "https://cdn.countryflags.com/thumbs/ecuador/flag-800.png" },
    { name: "Egypt", flagURL: "https://cdn.countryflags.com/thumbs/egypt/flag-800.png" },
    { name: "El Salvador", flagURL: "https://cdn.countryflags.com/thumbs/el-salvador/flag-800.png" },
    { name: "Equatorial Guinea", flagURL: "https://cdn.countryflags.com/thumbs/equatorial-guinea/flag-800.png" },
    { name: "Eritrea", flagURL: "https://cdn.countryflags.com/thumbs/eritrea/flag-800.png" },
    { name: "Estonia", flagURL: "https://cdn.countryflags.com/thumbs/estonia/flag-800.png" },
    { name: "Eswatini", flagURL: "https://cdn.countryflags.com/thumbs/eswatini/flag-800.png" },
    { name: "Ethiopia", flagURL: "https://cdn.countryflags.com/thumbs/ethiopia/flag-800.png" },
    { name: "Fiji", flagURL: "https://cdn.countryflags.com/thumbs/fiji/flag-800.png" },
    { name: "Finland", flagURL: "https://cdn.countryflags.com/thumbs/finland/flag-800.png" },
    { name: "France", flagURL: "https://cdn.countryflags.com/thumbs/france/flag-800.png" },
    { name: "Gabon", flagURL: "https://cdn.countryflags.com/thumbs/gabon/flag-800.png" },
    { name: "Gambia", flagURL: "https://cdn.countryflags.com/thumbs/gambia/flag-800.png" },
    { name: "Georgia", flagURL: "https://cdn.countryflags.com/thumbs/georgia/flag-800.png" },
    { name: "Germany", flagURL: "https://cdn.countryflags.com/thumbs/germany/flag-800.png" },
    { name: "Ghana", flagURL: "https://cdn.countryflags.com/thumbs/ghana/flag-800.png" },
    { name: "Greece", flagURL: "https://cdn.countryflags.com/thumbs/greece/flag-800.png" },
    { name: "Grenada", flagURL: "https://cdn.countryflags.com/thumbs/grenada/flag-800.png" },
    { name: "Guatemala", flagURL: "https://cdn.countryflags.com/thumbs/guatemala/flag-800.png" },
    { name: "Guinea", flagURL: "https://cdn.countryflags.com/thumbs/guinea/flag-800.png" },
    { name: "Guinea-Bissau", flagURL: "https://cdn.countryflags.com/thumbs/guinea-bissau/flag-800.png" },
    { name: "Guyana", flagURL: "https://cdn.countryflags.com/thumbs/guyana/flag-800.png" },
    { name: "Haiti", flagURL: "https://cdn.countryflags.com/thumbs/haiti/flag-800.png" },
    { name: "Honduras", flagURL: "https://cdn.countryflags.com/thumbs/honduras/flag-800.png" },
    { name: "Hungary", flagURL: "https://cdn.countryflags.com/thumbs/hungary/flag-800.png" },
    { name: "Iceland", flagURL: "https://cdn.countryflags.com/thumbs/iceland/flag-800.png" },
    { name: "India", flagURL: "https://cdn.countryflags.com/thumbs/india/flag-800.png" },
    { name: "Indonesia", flagURL: "https://cdn.countryflags.com/thumbs/indonesia/flag-800.png" },
    { name: "Iran", flagURL: "https://cdn.countryflags.com/thumbs/iran/flag-800.png" },
    { name: "Iraq", flagURL: "https://cdn.countryflags.com/thumbs/iraq/flag-800.png" },
    { name: "Ireland", flagURL: "https://cdn.countryflags.com/thumbs/ireland/flag-800.png" },
    { name: "Israel", flagURL: "https://cdn.countryflags.com/thumbs/israel/flag-800.png" },
    { name: "Italy", flagURL: "https://cdn.countryflags.com/thumbs/italy/flag-800.png" },
    { name: "Jamaica", flagURL: "https://cdn.countryflags.com/thumbs/jamaica/flag-800.png" },
    { name: "Japan", flagURL: "https://cdn.countryflags.com/thumbs/japan/flag-800.png" },
    { name: "Jordan", flagURL: "https://cdn.countryflags.com/thumbs/jordan/flag-800.png" },
    { name: "Kazakhstan", flagURL: "https://cdn.countryflags.com/thumbs/kazakhstan/flag-800.png" },
    { name: "Kenya", flagURL: "https://cdn.countryflags.com/thumbs/kenya/flag-800.png" },
    { name: "Kiribati", flagURL: "https://cdn.countryflags.com/thumbs/kiribati/flag-800.png" },
    { name: "Korea, North", flagURL: "https://cdn.countryflags.com/thumbs/korea-north/flag-800.png" },
    { name: "Korea, South", flagURL: "https://cdn.countryflags.com/thumbs/korea-south/flag-800.png" },
    { name: "Kosovo", flagURL: "https://cdn.countryflags.com/thumbs/kosovo/flag-800.png" },
    { name: "Kuwait", flagURL: "https://cdn.countryflags.com/thumbs/kuwait/flag-800.png" },
    { name: "Kyrgyzstan", flagURL: "https://cdn.countryflags.com/thumbs/kyrgyzstan/flag-800.png" },
    { name: "Laos", flagURL: "https://cdn.countryflags.com/thumbs/laos/flag-800.png" },
    { name: "Latvia", flagURL: "https://cdn.countryflags.com/thumbs/latvia/flag-800.png" },
    { name: "Lebanon", flagURL: "https://cdn.countryflags.com/thumbs/lebanon/flag-800.png" },
    { name: "Lesotho", flagURL: "https://cdn.countryflags.com/thumbs/lesotho/flag-800.png" },
    { name: "Liberia", flagURL: "https://cdn.countryflags.com/thumbs/liberia/flag-800.png" },
    { name: "Libya", flagURL: "https://cdn.countryflags.com/thumbs/libya/flag-800.png" },
    { name: "Liechtenstein", flagURL: "https://cdn.countryflags.com/thumbs/liechtenstein/flag-800.png" },
    { name: "Lithuania", flagURL: "https://cdn.countryflags.com/thumbs/lithuania/flag-800.png" },
    { name: "Luxembourg", flagURL: "https://cdn.countryflags.com/thumbs/luxembourg/flag-800.png" },
    { name: "Madagascar", flagURL: "https://cdn.countryflags.com/thumbs/madagascar/flag-800.png" },
    { name: "Malawi", flagURL: "https://cdn.countryflags.com/thumbs/malawi/flag-800.png" },
    { name: "Malaysia", flagURL: "https://cdn.countryflags.com/thumbs/malaysia/flag-800.png" },
    { name: "Maldives", flagURL: "https://cdn.countryflags.com/thumbs/maldives/flag-800.png" },
    { name: "Mali", flagURL: "https://cdn.countryflags.com/thumbs/mali/flag-800.png" },
    { name: "Malta", flagURL: "https://cdn.countryflags.com/thumbs/malta/flag-800.png" },
    { name: "Marshall Islands", flagURL: "https://cdn.countryflags.com/thumbs/marshall-islands/flag-800.png" },
    { name: "Mauritania", flagURL: "https://cdn.countryflags.com/thumbs/mauritania/flag-800.png" },
    { name: "Mauritius", flagURL: "https://cdn.countryflags.com/thumbs/mauritius/flag-800.png" },
    { name: "Mexico", flagURL: "https://cdn.countryflags.com/thumbs/mexico/flag-800.png" },
    { name: "Micronesia", flagURL: "https://cdn.countryflags.com/thumbs/micronesia/flag-800.png" },
    { name: "Moldova", flagURL: "https://cdn.countryflags.com/thumbs/moldova/flag-800.png" },
    { name: "Monaco", flagURL: "https://cdn.countryflags.com/thumbs/monaco/flag-800.png" },
    { name: "Mongolia", flagURL: "https://cdn.countryflags.com/thumbs/mongolia/flag-800.png" },
    { name: "Montenegro", flagURL: "https://cdn.countryflags.com/thumbs/montenegro/flag-800.png" },
    { name: "Morocco", flagURL: "https://cdn.countryflags.com/thumbs/morocco/flag-800.png" },
    { name: "Mozambique", flagURL: "https://cdn.countryflags.com/thumbs/mozambique/flag-800.png" },
    { name: "Myanmar", flagURL: "https://cdn.countryflags.com/thumbs/myanmar/flag-800.png" },
    { name: "Namibia", flagURL: "https://cdn.countryflags.com/thumbs/namibia/flag-800.png" },
    { name: "Nauru", flagURL: "https://cdn.countryflags.com/thumbs/nauru/flag-800.png" },
    { name: "Nepal", flagURL: "https://cdn.countryflags.com/thumbs/nepal/flag-800.png" },
    { name: "Netherlands", flagURL: "https://cdn.countryflags.com/thumbs/netherlands/flag-800.png" },
    { name: "New Zealand", flagURL: "https://cdn.countryflags.com/thumbs/new-zealand/flag-800.png" },
    { name: "Nicaragua", flagURL: "https://cdn.countryflags.com/thumbs/nicaragua/flag-800.png" },
    { name: "Niger", flagURL: "https://cdn.countryflags.com/thumbs/niger/flag-800.png" },
    { name: "Nigeria", flagURL: "https://cdn.countryflags.com/thumbs/nigeria/flag-800.png" },
    { name: "North Macedonia", flagURL: "https://cdn.countryflags.com/thumbs/north-macedonia/flag-800.png" },
    { name: "Norway", flagURL: "https://cdn.countryflags.com/thumbs/norway/flag-800.png" },
    { name: "Oman", flagURL: "https://cdn.countryflags.com/thumbs/oman/flag-800.png" },
    { name: "Pakistan", flagURL: "https://cdn.countryflags.com/thumbs/pakistan/flag-800.png" },
    { name: "Palau", flagURL: "https://cdn.countryflags.com/thumbs/palau/flag-800.png" },
    { name: "Palestine", flagURL: "https://cdn.countryflags.com/thumbs/palestine/flag-800.png" },
    { name: "Panama", flagURL: "https://cdn.countryflags.com/thumbs/panama/flag-800.png" },
    { name: "Papua New Guinea", flagURL: "https://cdn.countryflags.com/thumbs/papua-new-guinea/flag-800.png" },
    { name: "Paraguay", flagURL: "https://cdn.countryflags.com/thumbs/paraguay/flag-800.png" },
    { name: "Peru", flagURL: "https://cdn.countryflags.com/thumbs/peru/flag-800.png" },
    { name: "Philippines", flagURL: "https://cdn.countryflags.com/thumbs/philippines/flag-800.png" },
    { name: "Poland", flagURL: "https://cdn.countryflags.com/thumbs/poland/flag-800.png" },
    { name: "Portugal", flagURL: "https://cdn.countryflags.com/thumbs/portugal/flag-800.png" },
    { name: "Qatar", flagURL: "https://cdn.countryflags.com/thumbs/qatar/flag-800.png" },
    { name: "Romania", flagURL: "https://cdn.countryflags.com/thumbs/romania/flag-800.png" },
    { name: "Russia", flagURL: "https://cdn.countryflags.com/thumbs/russia/flag-800.png" },
    { name: "Rwanda", flagURL: "https://cdn.countryflags.com/thumbs/rwanda/flag-800.png" },
    { name: "Saint Kitts and Nevis", flagURL: "https://cdn.countryflags.com/thumbs/saint-kitts-and-nevis/flag-800.png" },
    { name: "Saint Lucia", flagURL: "https://cdn.countryflags.com/thumbs/saint-lucia/flag-800.png" },
    { name: "Saint Vincent and the Grenadines", flagURL: "https://cdn.countryflags.com/thumbs/saint-vincent-and-the-grenadines/flag-800.png" },
    { name: "Samoa", flagURL: "https://cdn.countryflags.com/thumbs/samoa/flag-800.png" },
    { name: "San Marino", flagURL: "https://cdn.countryflags.com/thumbs/san-marino/flag-800.png" },
    { name: "Sao Tome and Principe", flagURL: "https://cdn.countryflags.com/thumbs/sao-tome-and-principe/flag-800.png" },
    { name: "Saudi Arabia", flagURL: "https://cdn.countryflags.com/thumbs/saudi-arabia/flag-800.png" },
    { name: "Senegal", flagURL: "https://cdn.countryflags.com/thumbs/senegal/flag-800.png" },
    { name: "Serbia", flagURL: "https://cdn.countryflags.com/thumbs/serbia/flag-800.png" },
    { name: "Seychelles", flagURL: "https://cdn.countryflags.com/thumbs/seychelles/flag-800.png" },
    { name: "Sierra Leone", flagURL: "https://cdn.countryflags.com/thumbs/sierra-leone/flag-800.png" },
    { name: "Singapore", flagURL: "https://cdn.countryflags.com/thumbs/singapore/flag-800.png" },
    { name: "Slovakia", flagURL: "https://cdn.countryflags.com/thumbs/slovakia/flag-800.png" },
    { name: "Slovenia", flagURL: "https://cdn.countryflags.com/thumbs/slovenia/flag-800.png" },
    { name: "Solomon Islands", flagURL: "https://cdn.countryflags.com/thumbs/solomon-islands/flag-800.png" },
    { name: "Somalia", flagURL: "https://cdn.countryflags.com/thumbs/somalia/flag-800.png" },
    { name: "South Africa", flagURL: "https://cdn.countryflags.com/thumbs/south-africa/flag-800.png" },
    { name: "South Sudan", flagURL: "https://cdn.countryflags.com/thumbs/south-sudan/flag-800.png" },
    { name: "Spain", flagURL: "https://cdn.countryflags.com/thumbs/spain/flag-800.png" },
    { name: "Sri Lanka", flagURL: "https://cdn.countryflags.com/thumbs/sri-lanka/flag-800.png" },
    { name: "Sudan", flagURL: "https://cdn.countryflags.com/thumbs/sudan/flag-800.png" },
    { name: "Suriname", flagURL: "https://cdn.countryflags.com/thumbs/suriname/flag-800.png" },
    { name: "Sweden", flagURL: "https://cdn.countryflags.com/thumbs/sweden/flag-800.png" },
    { name: "Switzerland", flagURL: "https://cdn.countryflags.com/thumbs/switzerland/flag-800.png" },
    { name: "Syria", flagURL: "https://cdn.countryflags.com/thumbs/syria/flag-800.png" },
    { name: "Taiwan", flagURL: "https://cdn.countryflags.com/thumbs/taiwan/flag-800.png" },
    { name: "Tajikistan", flagURL: "https://cdn.countryflags.com/thumbs/tajikistan/flag-800.png" },
    { name: "Tanzania", flagURL: "https://cdn.countryflags.com/thumbs/tanzania/flag-800.png" },
    { name: "Thailand", flagURL: "https://cdn.countryflags.com/thumbs/thailand/flag-800.png" },
    { name: "Togo", flagURL: "https://cdn.countryflags.com/thumbs/togo/flag-800.png" },
    { name: "Tonga", flagURL: "https://cdn.countryflags.com/thumbs/tonga/flag-800.png" },
    { name: "Trinidad and Tobago", flagURL: "https://cdn.countryflags.com/thumbs/trinidad-and-tobago/flag-800.png" },
    { name: "Tunisia", flagURL: "https://cdn.countryflags.com/thumbs/tunisia/flag-800.png" },
    { name: "Turkey", flagURL: "https://cdn.countryflags.com/thumbs/turkey/flag-800.png" },
    { name: "Turkmenistan", flagURL: "https://cdn.countryflags.com/thumbs/turkmenistan/flag-800.png" },
    { name: "Tuvalu", flagURL: "https://cdn.countryflags.com/thumbs/tuvalu/flag-800.png" },
    { name: "Uganda", flagURL: "https://cdn.countryflags.com/thumbs/uganda/flag-800.png" },
    { name: "Ukraine", flagURL: "https://cdn.countryflags.com/thumbs/ukraine/flag-800.png" },
    { name: "United Arab Emirates", flagURL: "https://cdn.countryflags.com/thumbs/united-arab-emirates/flag-800.png" },
    { name: "United Kingdom", flagURL: "https://cdn.countryflags.com/thumbs/united-kingdom/flag-800.png" },
    { name: "United States", flagURL: "https://cdn.countryflags.com/thumbs/united-states/flag-800.png" },
    { name: "Uruguay", flagURL: "https://cdn.countryflags.com/thumbs/uruguay/flag-800.png" },
    { name: "Uzbekistan", flagURL: "https://cdn.countryflags.com/thumbs/uzbekistan/flag-800.png" },
    { name: "Vanuatu", flagURL: "https://cdn.countryflags.com/thumbs/vanuatu/flag-800.png" },
    { name: "Vatican City", flagURL: "https://cdn.countryflags.com/thumbs/vatican-city/flag-800.png" },
    { name: "Venezuela", flagURL: "https://cdn.countryflags.com/thumbs/venezuela/flag-800.png" },
    { name: "Vietnam", flagURL: "https://cdn.countryflags.com/thumbs/vietnam/flag-800.png" },
    { name: "Yemen", flagURL: "https://cdn.countryflags.com/thumbs/yemen/flag-800.png" },
    { name: "Zambia", flagURL: "https://cdn.countryflags.com/thumbs/zambia/flag-800.png" },
    { name: "Zimbabwe", flagURL: "https://cdn.countryflags.com/thumbs/zimbabwe/flag-800.png" }
];




  export const CountryFlag = ({ countryCode, className }) => {
    const country = countryInfo.find((info) => info.name === countryCode);
  
    if (country) {
      return <img src={country.flagURL} alt={`Flag of ${country.name}`} className={`flag-image ${className}`} style={{ width: '100px', height: 'auto' }} />;
    } else {
      return <span>No flag available</span>;
    }
  };